apiVersion: v1
kind: Namespace
metadata:
  name: showcase-model
  labels:
    app.kubernetes.io/part-of: kubernetes-ai-platform-showcase
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbun
  namespace: showcase-model
  labels:
    app.kubernetes.io/name: httpbun
    app.kubernetes.io/part-of: kubernetes-ai-platform-showcase
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbun
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbun
        app.kubernetes.io/part-of: kubernetes-ai-platform-showcase
    spec:
      automountServiceAccountToken: false
      containers:
        - name: httpbun
          image: sharat87/httpbun@sha256:405332d9050a731c80f406df5bde2e3efa731e324c0e8820af77710c5f633999
          imagePullPolicy: IfNotPresent
          env:
            - name: HTTPBUN_BIND
              value: 0.0.0.0:3090
          ports:
            - name: http
              containerPort: 3090
          readinessProbe:
            httpGet:
              path: /get
              port: http
            periodSeconds: 3
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: httpbun
  namespace: showcase-model
  labels:
    app.kubernetes.io/name: httpbun
    app.kubernetes.io/part-of: kubernetes-ai-platform-showcase
spec:
  selector:
    app.kubernetes.io/name: httpbun
  ports:
    - name: http
      port: 3090
      targetPort: http
